import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Andronov' at '31.10.17 11:35' with Gradle 2.9
 *
 * @author Andronov, @date 31.10.17 11:35
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    }
}
